# This file contains the configuration for the node

# General parameters
common:
  topics:
    input:
      points: "/velodyne_points"
    output:
      ground: "/ftfcd/debug/ground"
      clusters: "/ftfcd/debug/clusters"
      observations: /AS/P/ftfcd/observations

manager:
  publish_debug: true

dbscan:
  octreeResolution: 200
  eps: 2
  minPtsAux: 2 
  minPts: 3

ransac:
  ground_segmentation_mode: true              # True: Ransac / False: Linefit
  publish_ground: true                        # Publish ground
  publish_obstacle: true                      # Publish obstacle
  minz: -1                                    # min z value of the point cloud
  maxz: 1                                    # max z value of the point cloud
  max_x: 25                                   # max x value of the point cloud
  max_y: 10                                   # max y value of the point cloud
  min_y: -10                                  # min y value of the point cloud
  x_car_limit_p: 0.3                          # The 4 values of car limit are because
  x_car_limit_n: -0.3                         # there are parts of the car that are always
  y_car_limit_p: 0.3                          # reached by the LiDAR laser beams and same position
  y_car_limit_n: -0.3                         # No need to look for them always
  max_iterations: 400                         # max iterations of the ransac algorithm (https://en.wikipedia.org/wiki/Random_sample_consensus)
  dist_threshold: 0.1                         # distance threshold of the ransac algorithm   s'ha de quedar a 0.1 sino els cons perden massa punts
  plane_angle: 0.30                           # max angle of the plane 
  vis_outliers: false                         # visualize outliers
